### ISSUE TITLE
iphone 6+

### ISSUE THREAD

**Issue by UPMuling** [iBootBeta2/OXUL103-Jailbreak#11]
Buddy, we support you to do this, and will always support. I have an iPhone6 + that can help you test your IPA. If you like it. email muling656@live.cn

**Comment by fluffy66** [comment]
Hey man, in case my other E-mail doesn't work send it to pactofsteel42@gmail.com Thx!

**Comment by iBootBeta2** [comment]
Will do. Thanks, I'll send once I finished compiling the ipa.

**Comment by iHelloGoodBye8** [comment]
Hey man, in case my other E-mail doesn't work send it to pqfdd@live.com Thx!
