### ISSUE TITLE
GUYS!! I FOUND THIS ON HIS PROYECT

### ISSUE THREAD

**Issue by jailbreaklover** [iBootBeta2/OXUL103-Jailbreak#16]
[](https://github.com/iBootBeta2/OXUL103-Jailbreak/blob/master/OXUL103/OPENME)
This is a file that he put in. Just read it

**Comment by jailbreaklover** [comment]
[https://github.com/iBootBeta2/OXUL103-Jailbreak/blob/master/OXUL103/OPENME](url)

**Comment by thisistripping** [comment]
This was posted before he decided to do it he hasn't updated the files in 2 days so he hasn't removed them

**Comment by jailbreaklover** [comment]
okay, i just cheking her proyect

**Comment by jailbreaklover** [comment]
but maybe he change his mind and continue the proyect, i am rigth?

**Comment by iBootBeta2** [comment]
I'm continuing thanks :)
