### ISSUE TITLE
iPhone 6

### ISSUE THREAD

**Issue by msamuel002** [iBootBeta2/OXUL103-Jailbreak#24]
Hello,
Could you send me the ipa to msam9491@gmail.com please so I can help test it for iPhone 6? Thanks for all your work!

**Comment by iBootBeta2** [comment]
Sure!

**Comment by korg2009** [comment]
Hello,
Can you Send me too the ipa file for IPhone 6 please? Halil.kokorri@googlemail.com

I can help and  Test it and make a Feedback 👍
And thanks for all your work ✌🏻 (ps: Sry for My english im from Germany)
