### ISSUE TITLE
Hello,iPhone 6 plus

### ISSUE THREAD

**Issue by iHelloGoodBye8** [iBootBeta2/OXUL103-Jailbreak#26]
Hello,
Could you send me the ipa to pqfdd@live.com please so I can help test it for iPhone 6 plus? Thanks for all your work!

**Comment by iBootBeta2** [comment]
Sure.

**Comment by iHelloGoodBye8** [comment]
Can I send it now? Thank you！

**Comment by iBootBeta2** [comment]
You need to wait for completion of ipa, I'm still working on

**Comment by iHelloGoodBye8** [comment]
How long will it take? Can you send it to me after work?

**Comment by iBootBeta2** [comment]
Sure!

**Comment by iHelloGoodBye8** [comment]
OK, please send off my API test and thank you sincerely!

**Comment by iBootBeta2** [comment]
Sure, and that's okay!

**Comment by iHelloGoodBye8** [comment]
Ok, I'll wait for you！

**Comment by iHelloGoodBye8** [comment]
Do you have free time now? Can you send me IPA? My mailbox: pqfdd@live.com, I'll test you and give you feedback!

**Comment by thisistripping** [comment]
You need to wait like everyone else, he is yet to send out the IPA to anyone, I asked to be a tester a few days ago and still have not got it, it is up to iBoot to decide if he is willing to send it and when!

**Comment by jailbreaklover** [comment]
@iHelloGoodBye8 you need to be patient, he doesn't send ipa's for the rest of the people ho want to test the JB. Patient

**Comment by iHelloGoodBye8** [comment]
@jailbreaklover @thisistripping Have you tested this jailbreak?

**Comment by thisistripping** [comment]
No we have not as her have not received it!

**Comment by jailbreaklover** [comment]
Anyone that request the test of the JB hasn't

**Comment by iHelloGoodBye8** [comment]
@thisistripping @jailbreaklover Now I see！ Do you think this JB is real?

**Comment by jailbreaklover** [comment]
The only thing that sure we have is the JB is still working. So please don't press iBoot

**Comment by thisistripping** [comment]
Personally I would say I do as what is the point in wasting this time and effort. However, I am becoming sceptical as it is taking some time but I'm hoping for the best

**Comment by iHelloGoodBye8** [comment]
I doubt that it will take time, and I hope iBoot releases the Beta version shortly!

**Comment by jailbreaklover** [comment]
Maybe he released by the week

**Comment by iHelloGoodBye8** [comment]
Haha ^ ^)

**Comment by iHelloGoodBye8** [comment]
IBoot in order to find a sense of existence, even so, it is too immoral, no technology, but also force! Fuck it! @iBootBeta2
