### ISSUE TITLE
The Big of the fakes.

### ISSUE THREAD

**Issue by BadWolf-alfa** [iBootBeta2/OXUL103-Jailbreak#28]
Good for you, all people camming you. And waiting foro your Big fake Release.

Supossite you deleted the kernel_xploit.h file because of GeosNow no aprove you use...
Ah...good
Kernel_xploit.h (remember? You deleted)
https://github.com/iBootBeta2/OXUL103-Jailbreak/commit/a2edbe3ce0490e8470a13d0955b343c8387cdae6

And.... Oppps ....
Kernel_xploit.h date: december of 2016
https://github.com/BocuD/mach_portal_GUI/blob/master/mach_portal/mach_portal/kernel_sploit.h
Ops its same... Casuallity?....
GeosNow

And from your readme, all copied from:
https://github.com/matteyeux/extra_recipe/blob/master/README.md
And are xploit for 10.2 ....

Ops...
Big deal the Next time Guy..

**Comment by BadWolf-alfa** [comment]
The readme i say:
https://github.com/iBootBeta2/OXUL103-Jailbreak/blob/master/OXUL103/README

And you say in that its for 10.3x ha ha ha

**Comment by gzsobb** [comment]
This is a fake JB! In order to become famous!

**Comment by iHelloGoodBye8** [comment]
This JB is Fake！

**Comment by iHelloGoodBye8** [comment]
Release fake jailbreak, fuck you!

**Comment by gzsobb** [comment]
Release fake jailbreak, fuck you! @iBootBeta2

**Comment by iHelloGoodBye8** [comment]
IBoot in order to find a sense of existence, even so, it is too immoral, no technology, but also force! Fuck it!

**Comment by iBootBeta2** [comment]
Lol, salty? It's real! Kys

**Comment by BadWolf-alfa** [comment]
Real hahahaha 
.... Suck your balls its real...

**Comment by frapajohn** [comment]
@iBootBeta2 HOPE YOU TO GEN CANCER SOON!!!

**Comment by frapajohn** [comment]
Get*
