### ISSUE TITLE
How it's going with the jb

### ISSUE THREAD

**Issue by jailbreaklover** [iBootBeta2/OXUL103-Jailbreak#29]
@iBootBeta2 how go the progress of the JB?

**Comment by fluffy66** [comment]
Are you close to getting the ipa?

**Comment by iBootBeta2** [comment]
I need app icon, that's all!

**Comment by madoksystem** [comment]
Good afternoon :-)
If the jailbreak will be compatible with iphone 6 ios 10.3.2 please ?
And, if the ipa's getting done ?

**Comment by iBootBeta2** [comment]
Yes it will be, and I need an idea of the app image!

**Comment by jailbreaklover** [comment]
Make it from a famous people like King Yo Uh ... or I don't know 😂

**Comment by madoksystem** [comment]
Maybee we can help you for an idea, i mean it just left you to find an icon to release the jailbreak, such a great news for us 😜

Envoyé de mon iPhone

**Comment by madoksystem** [comment]
Like this stuff from iStock.com (copyrighted i know^^) you can create an icon with a "X" sign meaning of your "oXul" jailbreak :-)
Just an idea, not a bad thing at all hhh 🤓

**Comment by fluffy66** [comment]
Great! That's awesome man! Keep it up.

**Comment by jailbreaklover** [comment]
Cool!! @iBootBeta2 there you have it.

**Comment by iBootBeta2** [comment]
Yes ipa is almost done

**Comment by iBootBeta2** [comment]
@madoksystem  thanks!!
