### ISSUE TITLE
.ipa?

### ISSUE THREAD

**Issue by fluffy66** [iBootBeta2/OXUL103-Jailbreak#33]
Hey man not trying to rush art here but have you compiled the .ipa? I'm asking because you said you just needed an app icon and your good to go. Thanks!

**Comment by jailbreaklover** [comment]
Yes, it's true. But it you follow him in twitter. He had some problems but i contact him and he told me that he resolved but he need more time. The ipa is real but he told that he will released in this week or in july

**Comment by fluffy66** [comment]
Thanks! I appreciate the help!

**Comment by jailbreaklover** [comment]
And he is making a appinjector that can bring 1 year certificate the JB that the cydia impactor that brings 7 day certificate

**Comment by jailbreaklover** [comment]
Now I am the right hand of him. So any quiestion i can answer it.👍🏾

**Comment by fluffy66** [comment]
Ok great! Can't wait to get the .ipa.

**Comment by jailbreaklover** [comment]
I know😂😂 Me too. Well I will close the issue.
