### ISSUE TITLE
my email

### ISSUE THREAD

**Issue by fluffy66** [iBootBeta2/OXUL103-Jailbreak#34]
Hi guys! Now that the IPA is out please E-mail me at richardholtman10@gmail.com. Thanks!

**Comment by jailbreaklover** [comment]
I don't receive any ipa

**Comment by jailbreaklover** [comment]
Really

**Comment by fluffy66** [comment]
What? I thought is was out! I've been following iBootBeta2 on twitter and he said it was ready.

**Comment by thisistripping** [comment]
Just because it's ready doesn't mean its out

**Comment by jailbreaklover** [comment]
Yes but he need to add the vulnerability of the iOS and he will send us them the beta 1 first

**Comment by fluffy66** [comment]
He said You can jailbreak!

**Comment by jailbreaklover** [comment]
I am her right hand and I text him, I know what's really happening

**Comment by fluffy66** [comment]
oh ok I will wait thanks man for your time!

**Comment by jailbreaklover** [comment]
Thanks for you patience!!

**Comment by fluffy66** [comment]
Can you do me a favor as his right hand man? Send me the IPA when its out please it would be much appreciated.

**Comment by jailbreaklover** [comment]
He personal will send the ipa to all the person that want to test it.

**Comment by jailbreaklover** [comment]
But when I get it, i will send it. If iBoot can't send it all the email the ipa

**Comment by jailbreaklover** [comment]
I close this issue for now

**Comment by fluffy66** [comment]
OK great! Thx for your help jailbreaklover, I can see why he made you his right hand man. Take care.

**Comment by jailbreaklover** [comment]
Okay, good day!
