### ISSUE TITLE
Where are we exactly in this project?

### ISSUE THREAD

**Issue by fluffy66** [iBootBeta2/OXUL103-Jailbreak#35]
Hi. I'm confused. Where are we exactly in this project? Is beta 2 out?

**Comment by jailbreaklover** [comment]
No, for that iBoot need that we test the beta 1 and feedback. Then he will release the beta 2. I will leave this issue open to @iBootBeta2 to answer this issue.

**Comment by iBootBeta2** [comment]
Question resolved, issue ticket closed,
