### ISSUE TITLE
No rush

### ISSUE THREAD

**Issue by fluffy66** [iBootBeta2/OXUL103-Jailbreak#40]
Hey guys, just wanted to say that there is no rush for this JB. You guys are going up against a lot with apple's new filing system. Take your time. It's done when its done.

**Comment by iBootBeta2** [comment]
A lot of chaos at the moment, check out my twitter for daily OXUL Jailbreak news & updates!! @iBootBeta2

**Comment by fluffy66** [comment]
Will do Thanks!

**Comment by iBootBeta2** [comment]
That's ok

**Comment by iBootBeta2** [comment]
Thanks, I appreciate you and your responsibility.
