### ISSUE TITLE
Supplies

### ISSUE THREAD

**Issue by fluffy66** [iBootBeta2/OXUL103-Jailbreak#41]
We can't build the wall without supplies can we!

**Comment by fluffy66** [comment]
Seriously though this project is likely fake. Anybody asking for money via PayPal. Yeah not good. Sorry fellas.

**Comment by fluffy66** [comment]
We will have to wait for Pangu or Adam to give us a Jailbreak.

**Comment by jailbreaklover** [comment]
The JB is not fake. The only reason that @iBootBeta2 need money is to buy anew c+ coder program more professional.

**Comment by jailbreaklover** [comment]
But he still working on it!

**Comment by fluffy66** [comment]
We can't build the wall without supplies can we! That's the error I got when I opened "Yalu 103" on my iphone which turned out to be Home Depot.

**Comment by jailbreaklover** [comment]
😂😂 forget. what I say

**Comment by iBootBeta2** [comment]
This isn't Home Depot.

**Comment by madoksystem** [comment]
Fluffy66 Yalu103 is one of hack4zrus fake jailbreak, not the the ibootbeta2 one what the hell is going on around here lol
