### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by iosh4ck3r** [iBootBeta2/OXUL103-Jailbreak#56]
I would like to test this jailbreak. I'm not going to leak the ipa to the public if you give it to me. I created my own ios 10.3.x jailbreak and I would like to see how this works. I'm not going to give you my email, but you can join this discord: https://discord.gg/Ps9Yx9Y . You can private message me when you are there.

**Comment by jailbreaklover** [comment]
I need your email to send the JB , I you want I would let you my twitter account to send it private @EJailbreaklover

**Comment by iosh4ck3r** [comment]
I'm @BeastPro3

**Comment by iosh4ck3r** [comment]
I can't DM you.

**Comment by fluffy66** [comment]
Houston we have a problem.....

**Comment by iBootBeta2** [comment]
I've completed jailbreak ipa.

**Comment by thesatanicbostonian** [comment]
Then release it.
