### ISSUE TITLE
is this jailbreak ready

### ISSUE THREAD

**Issue by msamuel002** [iBootBeta2/OXUL103-Jailbreak#59]
is it ready for iPhone 6?

**Comment by fluffy66** [comment]
He'll let you know when its ready :)

**Comment by fluffy66** [comment]
I'm sure he's figuring out a way to bypass that impactor error.

**Comment by iBootBeta2** [comment]
Beta 1 was released, but a bog failure, Impactor had an error, beta 2 will fix. It will be released either tomorrow or today.
