### ISSUE TITLE
I'm available to test the beta's and stability of them!

### ISSUE THREAD

**Issue by thisistripping** [iBootBeta2/OXUL103-Jailbreak#9]
Hi, it's me again. I was reading through recently updated files and seen in Update,json that you need devices and people to test the beta's. I am willing to put my device at risk to test this and prove others that they are wrong! Thanks again,

**EDIT:** I am currently running 10.3.1, if need be can update to 10.3.2

**Comment by jailbreaklover** [comment]
I have a device that I can used for the test of the beta of this JB, if you want

**Comment by iBootBeta2** [comment]
Stay on 10.3.1, and sure! I'll get back to you with the .ipa file.

**Comment by thisistripping** [comment]
Thanks for the quick response and was hoping that you'd say that :P

**Comment by iBootBeta2** [comment]
Thanks.

**Comment by jailbreaklover** [comment]
I have an iPhone with 10.3 , can this version can help you with the test of the beta

**Comment by thisistripping** [comment]
Do you want me to provide an email for you to send me it to or you going to post it up here?

**Comment by iBootBeta2** [comment]
@jailbreaklover sure will! Lower the better :) @thisistripping sure.

**Comment by thisistripping** [comment]
irbeharis@gmail.com @iBootBeta2

**Comment by jailbreaklover** [comment]
All right! Thanks for all @iBootBeta2 ...

**Comment by iBootBeta2** [comment]
All good. Closing issue if that's okay.

**Comment by jailbreaklover** [comment]
Ohh .. I forgot my email eliotrpaganserrano@gmail.com

**Comment by iBootBeta2** [comment]
Thanks! Will text both of you the .ipa asap.

**Comment by jailbreaklover** [comment]
Okay

**Comment by jamie72** [comment]
Yep if u need another guy to test I can too. I got 6+ on 10.3.1

**Comment by jamie72** [comment]
jamiewarren72@gmail.com. My email if u like me to tests too

**Comment by iBootBeta2** [comment]
Sure, thanks @jamie72

**Comment by jamie72** [comment]
Hey man just to let u know I been with u on this when u started this jailbreak if u didn't  notice and by the way I do have your back on this 👍🏻👍🏻👍🏻

**Comment by iBootBeta2** [comment]
@jamie72  yeah dude, I've noticed. Thanks so much <3

**Comment by jailbreaklover** [comment]
@iBootBeta2 In my personal opinion, I am glad to let me try your beta, I hope that this protect will be successful :)

**Comment by thisistripping** [comment]
IrbeHaris liked your email
Spark by Readdle

**Comment by jailbreaklover** [comment]
Proyect**

**Comment by fluffy66** [comment]
Me too! Hope everything works out! We need a jailbreak its been long enough.

**Comment by jailbreaklover** [comment]
@fluffy66 do you want to be a collaborator with the JB , we need people with diferent devices to test it

**Comment by fluffy66** [comment]
Sure I'll test it. Send me the .ipa at richardholtman10@gmail.com.

**Comment by thisistripping** [comment]
We are yet to receive ours so we cannot until IBoot sends us it!

**Comment by jailbreaklover** [comment]
Soon we have our IPA , i will send it or someone of our collaborators

**Comment by jailbreaklover** [comment]
I hope for the day will have our IPA, or maybe for this week

**Comment by jailbreaklover** [comment]
@fluffy66 
Question:
What device of Apple you have in this moment?
Reason:
The JB support the following devices:
iPad 4 - 10.3.2
iPad Air - 10.3.2
iPad Air 2 - 10.3.2
iPad Mini - 10.3.1
iPhone 5 - 10.3.1
iPhone 5s - 10.3.2
iPhone 5c - 10.3.1
iPhone 6/+ - 10.3.1
iPhone 7/+ - 10.3 - 10.3.1
iPod Touch 6G - 10.3.1

Recommended version for the beta:
10.3 or 10.3.1

**Comment by fluffy66** [comment]
I have an iphone 6S plus running ios 10.3.1. He probably just forgot to put it in the list.

**Comment by jailbreaklover** [comment]
@fluffy66 , no it's just included to iPhone 6 to iPhone 6s+ ... so okay

**Comment by jailbreaklover** [comment]
@iBootBeta2 we have new people that want to test the JB

**Comment by Ankiiii** [comment]
So this jailbreak is legit?

**Comment by Ankiiii** [comment]
If it really is, I'd love to test. iPhone 5S 10.3.1

**Comment by fluffy66** [comment]
@Ankiiii 
We are hoping it is.

**Comment by jailbreaklover** [comment]
@Ankiiii we are waiting for @iBooBeta2, that give us the IPA in email to test it. You need to put your email if you want the JB to test it. But is decision of iBoot if he want to send it, in my case he will send the IPA

**Comment by fluffy66** [comment]
Hope he sends me the .ipa. I think its legit IMO.

**Comment by Ankiiii** [comment]
I do believe it's legit. I do. My email is:
tyler.clinton@icloud.com

**Comment by iBootBeta2** [comment]
Sure, I'm compiling the Ipa still. I'll give a message with ipa attached.

**Comment by jailbreaklover** [comment]
Okay @iBootBeta2, we will wait for it. Keep working brother and keep still, we will support in anything!

**Comment by xjssam23** [comment]
when deploy the jailbreak tool？

**Comment by iBootBeta2** [comment]
@xjssam23  "Will be released once @thisistripping and I confirm safe to release."
